### ISSUE TITLE
Show password not working on password filed .

### ISSUE THREAD

**Issue by gautamv16** [the-canonizer/canonizer-3.0-frontend#2082] opened 2024-08-27 11:18 UTC
Show password not working on password filed .
Please check overall password field for the same .
![passw](https://github.com/user-attachments/assets/805fdaf6-7070-4040-970e-1113f0e8fc6d)

**Comment by saniatg** [comment] 2024-08-30 03:44
Duplicate of issue
https://github.com/the-canonizer/Canonizer-Beta--Issue-Tracking/issues/1144

**Closed as completed by saniatg** 2024-08-30 03:44 UTC
Labels: bug
