### ISSUE TITLE
[object Object] showing as default text in Edit Summary field for camp statement

### ISSUE THREAD

**Issue by mark-shamy** [the-canonizer/canonizer-3.0-frontend#1059] opened 2023-05-27 22:28 UTC

**Comment by ashish76** [comment] 2023-05-30 04:30
Hi, @mark-shamy we are unable to reproduce the issue described in the title. Could you please check again and let us know if there are any specific cases or steps?

**Comment by mark-shamy** [comment] 2023-06-01 02:59
Will create recreation steps

**Comment by cd-ali-ehsan** [comment] 2023-06-01 03:00
Duplicate of https://github.com/the-canonizer/canonizer-3.0-frontend/issues/928

**Comment by rupalichavan9860** [comment] 2023-06-12 13:34
Verified on live

**Closed as completed by rupalichavan9860** 2023-06-12 13:34 UTC
Labels: bug
